spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/framepulse
    username: postgres
    password: root

  flyway:
    locations: classpath:/db/migration
    schemas: flyway
    baselineOnMigrate: true
    enabled: false