spring:
  cassandra:
    request:
      timeout: 10s
    contact-points: localhost
    port: 9042
    keyspace-name: framepulse
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    schema-action: none